ADD TABLE USERS(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
username VARCHAR(32) NOT NULL,
firstname VARCHAR(32) NOT NULL,
lastname VARCHAR(32) NOT NULL,
pwd VARCHAR(32) NOT NULL,
email VARCHAR(64) NOT NULL
);

ADD TABLE SYMBOLS(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
shortname VARCHAR(4) NOT NULL UNIQUE,
longname VARCHAR(32) NOT NULL UNIQUE,
val INT,
oldvals VARCHAR(32)
);

ADD TABLE CASHACCTS(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
accountnum INT NOT NULL,
currentamt FLOAT NOT NULL
);

ADD TABLE PORTFOLIOS(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(32) NOT NULL,
userid INT NOT NULL where PORTFOLIOS.userid = USERS.id,
cashacct INT NOT NULL where PORTFOLIOS.cashacct = CASHACCTS.id,
stocks LONGTEXT
);

ADD TABLE TRANSACTIONS(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
cashacct INT NOT NULL where TRANSACTIONS.cashacct = CASHACCTS.id,
madeby INT NOT NULL WHERE TRANSACTIONS.madeby = USERS.id,
foramt INT NOT NULL,
transtime TIMESTAMP NOT NULL,
);